In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df = pd.read_csv('../cleaned_datasets/gurgaon_properties_cleaned_v2.csv')

In [15]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,...,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,flat,signature global park 4,sector 36,0.82,7585.0,1081.0,Super Built up area 1081(100.43 sq.m.)Carpet a...,3,2,2,...,1081.0,NaN,650.0,0,0,0,0,0,0,8
1,flat,smart world gems,sector 89,0.95,8600.0,1105.0,Carpet area: 1103 (102.47 sq.m.),2,2,2,...,NaN,NaN,1103.0,1,1,0,0,0,0,38
2,flat,pyramid elite,sector 86,0.46,79.0,58228.0,Carpet area: 58141 (5401.48 sq.m.),2,2,1,...,NaN,NaN,58141.0,0,0,0,0,0,0,15
3,flat,breez global hill view,sohna road,0.32,5470.0,585.0,Built Up area: 1000 (92.9 sq.m.)Carpet area: 5...,2,2,1,...,NaN,1000.0,585.0,0,0,0,0,0,0,49
4,flat,bestech park view sanskruti,sector 92,1.60,8020.0,1995.0,Super Built up area 1995(185.34 sq.m.)Built Up...,3,4,3+,...,1995.0,1615.0,1476.0,0,1,0,0,1,1,174

In [16]:
df.shape

(3803, 23)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3803 entries, 0 to 3802
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   property_type        3803 non-null   object
 1   society              3802 non-null   object
 2   sector               3803 non-null   object
 3   price                3785 non-null   float64
 4   price_per_sqft       3785 non-null   float64
 5   area                 3785 non-null   float64
 6   areaWithType         3803 non-null   object
 7   bedRoom              3803 non-null   int64
 8   bathroom             3803 non-null   int64
 9   balcony              3803 non-null   object
 10  floorNum             3784 non-null   float64
 11  facing               2698 non-null   object
 12  agePossession        3803 non-null   object
 13  super_built_up_area  1915 non-null   float64
 14  built_up_area        1733 non-null   float64
 15  carpet_area          1944 non-null   float64
 16  study room           3803 non-null   int64
 17  servant room         3803 non-null   int64
 18  store room           3803 non-null   int64
 19  pooja room           3803 non-null   int64
 20  others               3803 non-null   int64
 21  furnishing_type      3803 non-null   int64
 22  luxury_score         3803 non-null   int64
dtypes: float64(7), int64(9), object(7)
memory usage: 683.5+ KB

In [18]:
df.duplicated().sum()

np.int64(126)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.head()

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,...,super_built_up_area,built_up_area,carpet_area,study room,servant room,store room,pooja room,others,furnishing_type,luxury_score
0,flat,signature global park 4,sector 36,0.82,7585.0,1081.0,Super Built up area 1081(100.43 sq.m.)Carpet a...,3,2,2,...,1081.0,NaN,650.0,0,0,0,0,0,0,8
1,flat,smart world gems,sector 89,0.95,8600.0,1105.0,Carpet area: 1103 (102.47 sq.m.),2,2,2,...,NaN,NaN,1103.0,1,1,0,0,0,0,38
2,flat,pyramid elite,sector 86,0.46,79.0,58228.0,Carpet area: 58141 (5401.48 sq.m.),2,2,1,...,NaN,NaN,58141.0,0,0,0,0,0,0,15
3,flat,breez global hill view,sohna road,0.32,5470.0,585.0,Built Up area: 1000 (92.9 sq.m.)Carpet area: 5...,2,2,1,...,NaN,1000.0,585.0,0,0,0,0,0,0,49
4,flat,bestech park view sanskruti,sector 92,1.60,8020.0,1995.0,Super Built up area 1995(185.34 sq.m.)Built Up...,3,4,3+,...,1995.0,1615.0,1476.0,0,1,0,0,1,1,174

### property_type

In [23]:
%pip install --upgrade matplotlib

Collecting matplotlib
  Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.25 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=9 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.3 MB 1.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.0/9.3 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/9.3 MB 1.6 MB/s eta 0:00:05
   -------- ------------------------------- 2.1/9.3 MB 1.9 MB/s eta 0:00:04
   ----------- ---------------------------- 2.6/9.3 MB 2.0 MB/s eta 0:00:04
   --------------- ------------------------ 3.7/9.3 MB 2.3 MB/s eta 0:00:03
   ----------------- ---------------------- 4.2/9.3 MB 2.4 MB/s eta 0:00:03
   ---------------------- ----------------- 5.2/9.3 MB 2.7 MB/s eta 0:00:02
   ----------------------- ---------------- 5.5/9.3 MB 2.7 MB/s eta 0:00:02
   ------------------------- -------------- 6.0/9.3 MB 2.7 MB/s eta 0:00:02
   ------------------------------ --------- 7.1/9.3 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 8.1/9.3 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 3.1 MB/s  0:00:03
Installing collected packages: matplotlib
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages)
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\Users\\shivam\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\matplotlib\\backends\\_backend_agg.cp313-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

In [25]:
import sys
import matplotlib

print(sys.version)
print(matplotlib.__version__)
print(matplotlib.__file__)

3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)]
3.10.7
c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\__init__.py

In [26]:
import os
import matplotlib

backend_path = os.path.join(
    os.path.dirname(matplotlib.__file__),
    "backends",
    "backend_agg.py"
)

print(backend_path)
print(os.path.exists(backend_path))

c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\backends\backend_agg.py
False

In [28]:
%pip uninstall -y matplotlib
%pip cache purge
%pip install --no-cache-dir matplotlib==3.10.7

Found existing installation: matplotlib 3.11.0
Note: you may need to restart the kernel to use updated packages.

error: uninstall-no-record-file

× Cannot uninstall matplotlib 3.11.0
╰─> The package's contents are unknown: no RECORD file was found for matplotlib.

hint: You might be able to recover from this via: pip install --ignore-installed --no-deps matplotlib==3.11.0

Files removed: 1742 (1087.8 MB)
Directories removed: 21
Note: you may need to restart the kernel to use updated packages.
Collecting matplotlib==3.10.7
  Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (2.3.5)
Requirement already satisfied: packaging>=20.0 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (25.0)
Requirement already satisfied: pillow>=8 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib==3.10.7) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib==3.10.7) (1.17.0)
Downloading matplotlib-3.10.7-cp313-cp313-win_amd64.whl (8.1 MB)
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.1 MB 988.7 kB/s eta 0:00:08
   --- ------------------------------------ 0.8/8.1 MB 1.2 MB/s eta 0:00:07
   ----- ---------------------------------- 1.0/8.1 MB 1.3 MB/s eta 0:00:06
   ------- -------------------------------- 1.6/8.1 MB 1.4 MB/s eta 0:00:05
   ---------- ----------------------------- 2.1/8.1 MB 1.6 MB/s eta 0:00:04
   ------------ --------------------------- 2.6/8.1 MB 1.7 MB/s eta 0:00:04
   --------------- ------------------------ 3.1/8.1 MB 1.8 MB/s eta 0:00:03
   ------------------ --------------------- 3.7/8.1 MB 2.0 MB/s eta 0:00:03
   --------------------- ------------------ 4.5/8.1 MB 2.1 MB/s eta 0:00:02
   ------------------------- -------------- 5.2/8.1 MB 2.3 MB/s eta 0:00:02
   ----------------------------- ---------- 6.0/8.1 MB 2.4 MB/s eta 0:00:01
   ------------------------------------ --- 7.3/8.1 MB 2.6 MB/s eta 0:00:01
   -------------------------------------- - 7.9/8.1 MB 2.6 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 2.7 MB/s  0:00:03
Installing collected packages: matplotlib
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.11.0
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages)
error: uninstall-no-record-file

× Cannot uninstall matplotlib 3.11.0
╰─> The package's contents are unknown: no RECORD file was found for matplotlib.

hint: You might be able to recover from this via: pip install --ignore-installed --no-deps matplotlib==3.11.0

In [29]:
df["property_type"].value_counts().plot(kind="bar")

ImportError: cannot import name 'backend_agg' from 'matplotlib.backends' (c:\Users\shivam\AppData\Local\Programs\Python\Python313\Lib\site-packages\matplotlib\backends\__init__.py)

#### Observations

- Flats are in majority(75 percent) and there are less number of houses(~25 percent)
- No missing values

### society

In [ ]:
df['society'].value_counts().shape

In [ ]:
df['society'].value_counts()

In [ ]:
df[df['society'] != 'independent']['society'].value_counts(normalize=True).cumsum().head(75)

In [ ]:
society_counts = df['society'].value_counts()

# Frequency distribution for societies
frequency_bins = {
    "Very High (>100)": (society_counts > 100).sum(),
    "High (50-100)": ((society_counts >= 50) & (society_counts <= 100)).sum(),
    "Average (10-49)": ((society_counts >= 10) & (society_counts < 50)).sum(),
    "Low (2-9)": ((society_counts > 1) & (society_counts < 10)).sum(),
    "Very Low (1)": (society_counts == 1).sum()
}
frequency_bins

In [ ]:
# top 10 socities
df[df['society'] != 'independent']['society'].value_counts().head(10).plot(kind='bar')

In [ ]:
df['society'].isnull().sum()

In [ ]:
df[df['society'].isnull()]

#### Observations

- Around 13% properties comes under independent tag.
- There are 675 societies. 
- The top 75 societies have 50 percent of the preperties and the rest 50 percent of the properties come under the remaining 600 societies
    - Very High (>100): Only 1 society has more than 100 listings.
    - High (50-100): 2 societies have between 50 to 100 listings.
    - Average (10-49): 92 societies fall in this range with 10 to 49 listings each.
    - Low (2-9): 273 societies have between 2 to 9 listings.
    - Very Low (1): A significant number, 308 societies, have only 1 listing.
- 1 missing value

### sector

In [ ]:
# unique sectors
df['sector'].value_counts().shape

In [ ]:
# top 10 sectors
df['sector'].value_counts().head(10).plot(kind='bar')

In [ ]:
# Frequency distribution for sectors
sector_counts = df['sector'].value_counts()

sector_frequency_bins = {
    "Very High (>100)": (sector_counts > 100).sum(),
    "High (50-100)": ((sector_counts >= 50) & (sector_counts <= 100)).sum(),
    "Average (10-49)": ((sector_counts >= 10) & (sector_counts < 50)).sum(),
    "Low (2-9)": ((sector_counts > 1) & (sector_counts < 10)).sum(),
    "Very Low (1)": (sector_counts == 1).sum()
}

sector_frequency_bins

#### Observations

- There are a total of 104 unique sectors in the dataset.
- Frequency distribution of sectors:
    - Very High (>100): 3 sectors have more than 100 listings.
    - High (50-100): 25 sectors have between 50 to 100 listings.
    - Average (10-49): A majority, 60 sectors, fall in this range with 10 to 49 listings each.
    - Low (2-9): 16 sectors have between 2 to 9 listings.
    - Very Low (1): Interestingly, there are no sectors with only 1 listing.

### Price

In [ ]:
df['price'].isnull().sum()

In [ ]:
df['price'].describe()

In [ ]:
sns.histplot(df['price'], kde=True, bins=50)

In [ ]:
sns.boxplot(x=df['price'], color='lightgreen')
plt.grid()

- Descriptive Statistics:

    - Count: There are 3,660 non-missing price entries.
    - Mean Price: The average price is approximately 2.53 crores.
    - Median Price: The median (or 50th percentile) price is 1.52 crores.
    - Standard Deviation: The prices have a standard deviation of 2.98, indicating variability in the prices.
    - Range: Prices range from a minimum of 0.07 crores to a maximum of 31.5 crores.
    - IQR: The interquartile range (difference between 75th and 25th percentile) is from 0.95 crores to 2.75 crores.


- Visualizations:

    - Distribution: The histogram indicates that most properties are priced in the lower range (below 5 crores), with a few properties going beyond 10 crores.
    - Box Plot: The box plot showcases the spread of the data and potential outliers. Properties priced above approximately 10 crores might be considered outliers as they lie beyond the upper whisker of the box plot.
 

- Missing Values: There are 17 missing values in the price column.

In [ ]:
# Skewness and Kurtosis
skewness = df['price'].skew()
kurtosis = df['price'].kurt()

print(skewness,kurtosis)

**Skewness**: The price distribution has a skewness of approximately 3.28, indicating a positive skew. This means that the distribution tail is skewed to the right, which aligns with our observation from the histogram where most properties have prices on the lower end with a few high-priced properties.

**Kurtosis**: The kurtosis value is approximately 14.93. A kurtosis value greater than 3 indicates a distribution with heavier tails and more outliers compared to a normal distribution.

In [ ]:
# Quantile Analysis
quantiles = df['price'].quantile([0.01, 0.05, 0.95, 0.99])

quantiles

Quantile Analysis:

- 1% Quantile: Only 1% of properties are priced below 0.25 crores.
- 5% Quantile: 5% of properties are priced below 0.37 crores.
- 95% Quantile: 95% of properties are priced below 8.5 crores.
- 99% Quantile: 99% of properties are priced below 15.26 crores, indicating that very few properties are priced above this value.

In [ ]:
# Identify potential outliers using IQR method
Q1 = df['price'].describe()['25%']
Q3 = df['price'].describe()['75%']
IQR = Q3 - Q1

IQR

In [ ]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(lower_bound, upper_bound)

In [ ]:
outliers = df[(df['price'] < lower_bound) | (df['price'] > upper_bound)]
outliers.shape

In [ ]:
outliers['price'].describe()

Outliers Analysis (using IQR method):

- Based on the IQR method, there are 425 properties considered as outliers.
- These outliers have an average price of approximately 9.24 crores.
- The range for these outliers is from 5.46 crores to 31.5 crores.

In [ ]:
# price binning
bins = [0, 1, 2, 3, 5, 10, 20, 50]
bin_labels = ["0-1", "1-2", "2-3", "3-5", "5-10", "10-20", "20-50"]
pd.cut(df['price'], bins=bins, labels=bin_labels, right=False).value_counts().sort_index().plot(kind='bar')

- The majority of properties are priced in the "1-2 crores" and "2-3 crores" ranges.
- There's a significant drop in the number of properties priced above "5 crores."

In [ ]:
# ecdf plot
ecdf = df['price'].value_counts().sort_index().cumsum() / len(df['price'])
plt.plot(ecdf.index, ecdf, marker='.', linestyle='none')
plt.grid()

In [ ]:
plt.figure(figsize=(15, 6))

# Distribution plot without log transformation
plt.subplot(1, 2, 1)
sns.histplot(df['price'], kde=True, bins=50, color='skyblue')
plt.title('Distribution of Prices (Original)')
plt.xlabel('Price (in Crores)')
plt.ylabel('Frequency')

# Distribution plot with log transformation
plt.subplot(1, 2, 2)
sns.histplot(np.log1p(df['price']), kde=True, bins=50, color='lightgreen')
plt.title('Distribution of Prices (Log Transformed)')
plt.xlabel('Log(Price)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

np.log1p(x): This function computes the natural logarithm of 1+x. 
It's designed to provide more accurate results for values of x that are very close to zero.

Using np.log1p helps in transforming the price column while ensuring that any value (including zero, if present) is handled appropriately. When we need to reverse the transformation, we can use np.expm1 which computes e^x-1

In [ ]:
skewness = np.log1p(df['price']).skew()
kurtosis = np.log1p(df['price']).kurt()

print(skewness,kurtosis)

In [ ]:
plt.figure(figsize=(15, 6))

# Distribution plot without log transformation
plt.subplot(1, 2, 1)
sns.boxplot(df['price'], color='skyblue')
plt.title('Distribution of Prices (Original)')
plt.xlabel('Price (in Crores)')
plt.ylabel('Frequency')

# Distribution plot with log transformation
plt.subplot(1, 2, 2)
sns.boxplot(np.log1p(df['price']), color='lightgreen')
plt.title('Distribution of Prices (Log Transformed)')
plt.xlabel('Log(Price)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.show()

### price_per_sqft

In [ ]:
df['price_per_sqft'].isnull().sum()

In [ ]:
df['price_per_sqft'].describe()

In [ ]:
sns.histplot(df['price_per_sqft'], bins=50, color='skyblue', kde=True)

Most properties have a price_per_sqft ranging between approximately ₹0 and ₹40,000. There is a significant concentration in the lower range, with a few properties having exceptionally high price_per_sqft.

In [ ]:
sns.boxplot(df['price_per_sqft'], color='lightgreen')

The box plot clearly shows several outliers, especially on the higher side. The interquartile range (IQR) is relatively compact, but there are many data points beyond the "whiskers" of the box plot, indicating potential outliers

#### Observations

- Potential Outliers
- Right Skewed
- 17 missing values

### bedRoom

In [ ]:
df['bedRoom'].isnull().sum()

In [ ]:
df['bedRoom'].value_counts().sort_index().plot(kind='bar')

In [ ]:
df['bedRoom'].value_counts(normalize=True).head().plot(kind='pie',autopct='%0.2f%%')

### bathroom

In [ ]:
df['bathroom'].isnull().sum()

In [ ]:
df['bathroom'].value_counts().sort_index().plot(kind='bar')

In [ ]:
df['bathroom'].value_counts(normalize=True).head().plot(kind='pie',autopct='%0.2f%%')

In [ ]:
df.head()

### balcony

In [ ]:
df['balcony'].isnull().sum()

In [ ]:
df['balcony'].value_counts().plot(kind='bar')

In [ ]:
df['balcony'].value_counts(normalize=True).head().plot(kind='pie',autopct='%0.2f%%')

In [ ]:
### floorNum

In [ ]:
df.iloc[:,10:].head()

In [ ]:
df['floorNum'].isnull().sum()

In [ ]:
df['floorNum'].describe()

In [ ]:
df['floorNum'].value_counts().sort_index().plot(kind='bar')

In [ ]:
sns.boxplot(df['floorNum'], color='lightgreen')

- The majority of the properties lie between the ground floor (0) and the 25th floor.
- Floors 1 to 4 are particularly common, with the 3rd floor being the most frequent.
- There are a few properties located at higher floors, but their frequency is much lower.
- The box plot reveals that the majority of the properties are concentrated around the lower floors. The interquartile range (IQR) lies between approximately the 2nd and 10th floors.
- Data points beyond the "whiskers" of the box plot, especially on the higher side, indicate potential outliers.

### facing

In [ ]:
df['facing'].isnull().sum()

In [ ]:
df['facing'].fillna('NA',inplace=True)

In [ ]:
df['facing'].value_counts()

### agePossession

In [ ]:
df['agePossession'].isnull().sum()

In [ ]:
df['agePossession'].value_counts()

### areas

In [ ]:
# super built up area
df['super_built_up_area'].isnull().sum()

In [ ]:
df['super_built_up_area'].describe()

In [ ]:
sns.histplot(df['super_built_up_area'].dropna(), bins=50, color='skyblue', kde=True)

In [ ]:
sns.boxplot(df['super_built_up_area'].dropna(), color='lightgreen')

- Most properties have a super built-up area ranging between approximately 1,000 sq.ft and 2,500 sq.ft.
- There are a few properties with a significantly larger area, leading to a right-skewed distribution.
- The interquartile range (IQR) lies between roughly 1,480 sq.ft and 2,215 sq.ft, indicating that the middle 50% of the properties fall within this range.
- There are several data points beyond the upper "whisker" of the box plot, indicating potential outliers. These are properties with an unusually large super built-up area.

In [ ]:
# built up area
df['built_up_area'].isnull().sum()

In [ ]:
df['built_up_area'].describe()

In [ ]:
sns.histplot(df['built_up_area'].dropna(), bins=50, color='skyblue', kde=False)

In [ ]:
sns.boxplot(df['built_up_area'].dropna(), color='lightgreen')

- Most properties have a built-up area ranging roughly between 500 sq.ft and 3,500 sq.ft.
- There are very few properties with a much larger built-up area, leading to a highly right-skewed distribution.
- The box plot confirms the presence of significant outliers on the higher side. The data's interquartile range (IQR) is relatively compact, but the "whiskers" of the box plot are stretched due to the outliers.


The presence of extreme values, especially on the higher side, suggests that there may be outliers or data errors. This could also be due to some properties being exceptionally large, like a commercial complex or an entire building being listed.

In [ ]:
# carpet area
df['carpet_area'].isnull().sum()

In [ ]:
df['carpet_area'].describe()

In [ ]:
sns.histplot(df['carpet_area'].dropna(), bins=50, color='skyblue', kde=False)

In [ ]:
sns.boxplot(df['carpet_area'].dropna(), color='lightgreen')

In [ ]:
df.iloc[:,16:]

### additional rooms

In [ ]:
plt.figure(figsize=(20, 12))

# Create a subplot of pie charts for each room type
for idx, room in enumerate(['study room','servant room','store room','pooja room','others'], 1):
    ax = plt.subplot(2, 3, idx)
    df[room].value_counts().plot.pie(autopct='%1.1f%%', startangle=90, ax=ax)
    plt.title(f'Distribution of {room.title()}')
    plt.ylabel('')

plt.tight_layout()
plt.show()

### furnishing_type

In [ ]:
df['furnishing_type'].value_counts()

In [ ]:
df['furnishing_type'].value_counts().plot(kind='pie',autopct='%0.2f%%')

### luxury score

In [ ]:
df['luxury_score'].isnull().sum()

In [ ]:
df['luxury_score'].describe()

In [ ]:
sns.histplot(df['luxury_score'], bins=50, color='skyblue', kde=True)

In [ ]:
sns.boxplot(df['luxury_score'], color='lightgreen')

The luxury score distribution has multiple peaks, suggesting a multi-modal distribution. There's a significant number of properties with lower luxury scores (around 0-50), and another peak is observed around the 110-130 range.

The box plot reveals that the majority of the properties have luxury scores between approximately 30 and 110. The interquartile range (IQR) lies between these values.

In [ ]:
df.head()